### ISSUE TITLE
Allow mocking a function that isn't linked into the exe

### ISSUE THREAD

**Issue by ugoren** [hjagodzinski/C-Mock#11]
When linking a test executable, we sometimes don't want to link it with all the libraries that are used in production. Mocking is very useful for this - if you mock all functions in a library, you don't need to link with the library itself. But C-mock searches for the real function with `dlsym`, and fails if it doesn't exist. So you have to link with it.

In my company linkage is a mess, so we have a local change that checks if the function exists only if we actually try to call it. This is very useful for us.
You can see the code in [a branch in my clone](https://github.com/hjagodzinski/C-Mock/compare/master...ugoren:allow_no_real).

But this changes behavior unconditionally, so I don't think it's appropriate for merge.

The only difficulty is how can we make it conditional. There are may alternatives, such as:

- Compile time switch (e.g. `make ALLOW_MISSING=1`).
- A separate set of macros (e.g. `CMOCK_MOCK_FUNCTIONn_ALLOW_MISSING`).
- When using a mock class, a variation of `CMockMocker` (e.g. `CMockMockerAllowMissing`).
- A macro defined by used before defining mocks (e.g. `#define CMOCK_ALLOW_MISSING 1`).

Can we add this functionality?

Thanks.

**Comment by hjagodzinski** [comment]
Sorry for late reply. I would opt for alternative approach. A lazy loading of a real function. As long as a given function is not mocked no error will be thrown even if it's not available.

**Comment by hjagodzinski** [comment]
A situation in which you call a function which you neither linked with or mocked I see as a bug. I would make a lazy loading the default behaviour.

**Comment by ugoren** [comment]
Thanks. I'll prepare the code and submit a pull request.

**Comment by hjagodzinski** [comment]
👍

**Comment by ugoren** [comment]
Submitted pull request. CI passed.

BTW, C-Mock now fails to compile with latest Google Mock.
The problem is with the old macros, which rely more heavily on Google Mock
internals than the old ones.

On Mon, May 7, 2018 at 2:52 PM, Hubert Jagodziński <notifications@github.com

**Comment by hjagodzinski** [comment]
Can you create an issue on that so we can address it as a distinct problem?

**Comment by ugoren** [comment]
I'm not sure what you see as a distinct problem.

**Comment by hjagodzinski** [comment]
I have in mind _C-Mock now fails to compile with latest Google Mock._

**Comment by ugoren** [comment]
Ah, sure
