### ISSUE TITLE
Compilation Errors when using Google test version 1.10

### ISSUE THREAD

**Issue by fpskuji** [hjagodzinski/C-Mock#15]
I am using google test as a framework for my unit testing. And I am also studying  ways on how unit tests can be made as simple as possible and that's where I encountered this extension.
However when I used it for testing C functions there are build errors I encountered when compiling my test program
[compile_error.log](https://github.com/hjagodzinski/C-Mock/files/4448044/compile_error.log)

It failed to compile my source file **wlan_lib_mocker.cpp:**
`#include "wlan_lib_mocker.h"

CMOCK_MOCK_FUNCTION1(wlanlibmocker, getResponse, int(int));`

**wlan_lib_mocker.h contains:**
`#ifndef WLAN_LIB_MOCKER_H
#define WLAN_LIB_MOCKER_H

#include <cmock/cmock.h>

#include "wlan_lib.h"

class wlanlibmocker : public CMockMocker\<wlanlibmocker\>
{
public:
    MOCK_METHOD1(getResponse, int (int));
};

#endif /* WLAN_LIB_MOCKER_H */`

**The wlan_lib.h header file contains just the function prototype for getResponse()**

I am not sure if I am doing something wrong in here or there is something I've missed based on the instruction given on how to use C Mock. Other than this the main.cpp file just contains the main function which will run googletest's macro for running all tests and a test_driver.cpp for creating test cases.

**Comment by hjagodzinski** [comment]
@fpskuji have you managed to solve the compilation errors?
