### ISSUE TITLE
error: ‘std::tr1’ has not been declared

### ISSUE THREAD

**Issue by nsmohan** [hjagodzinski/C-Mock#16]
I am getting this error when I am doing a make within the C-Mock folder. 

  231 |     GTEST_COMPILE_ASSERT_(::std::tr1::tuple_size< \
      |                                  ^~~
add_function_mock.cc:3:1: note: in expansion of macro ‘IMPLEMENT_FUNCTION_MOCK2’
    3 | IMPLEMENT_FUNCTION_MOCK2(AddFunctionMock, add, int(int, int));
      | ^~~~~~~~~~~~~~~~~~~~~~~~
/home/nmohan/C-Mock/include/cmock/cmock-function-mockers.h:232:52: error: expected primary-expression before ‘>’ token
  232 |     ::testing::internal::Function<F>::ArgumentTuple>::value == 2, \
      |                                                    ^
add_function_mock.cc:3:1: note: in expansion of macro ‘IMPLEMENT_FUNCTION_MOCK2’
    3 | IMPLEMENT_FUNCTION_MOCK2(AddFunctionMock, add, int(int, int));
      | ^~~~~~~~~~~~~~~~~~~~~~~~
/home/nmohan/C-Mock/include/cmock/cmock-function-mockers.h:232:55: error: ‘::value’ has not been declared
  232 |     ::testing::internal::Function<F>::ArgumentTuple>::value == 2, \
      |                                                       ^~~~~
add_function_mock.cc:3:1: note: in expansion of macro ‘IMPLEMENT_FUNCTION_MOCK2’
    3 | IMPLEMENT_FUNCTION_MOCK2(AddFunctionMock, add, int(int, int));
      | ^~~~~~~~~~~~~~~~~~~~~~~~
In file included from /home/nmohan/C-Mock/include/cmock/cmock.h:38,
                 from add_function_mock.h:4,
                 from add_function_mock.cc:1:
add_function_mock.cc: In member function ‘testing::internal::MockSpec<int(int, int)>& AddFunctionMock::cmock_func(const testing::Matcher<int>&, const testing::Matcher<int>&)’:
/home/nmohan/C-Mock/include/cmock/cmock-function-mockers.h:241:23: error: cannot bind non-const lvalue reference of type ‘testing::internal::MockSpec<int(int, int)>&’ to an rvalue of type ‘testing::internal::MockSpec<int(int, int)>’
  241 |     return mocker.With(cmock_a1, cmock_a2); \
      |            ~~~~~~~~~~~^~~~~~~~~~~~~~~~~~~~
add_function_mock.cc:3:1: note: in expansion of macro ‘IMPLEMENT_FUNCTION_MOCK2’
    3 | IMPLEMENT_FUNCTION_MOCK2(AddFunctionMock, add, int(int, int));
      | ^~~~~~~~~~~~~~~~~~~~~~~~
make[1]: *** [Makefile:19: add_function_mock.o] Error 1
make[1]: Leaving directory '/home/nmohan/C-Mock/test'
make: *** [Makefile:16: test/cmock_test] Error 2

$gcc --version
gcc (Ubuntu 9.3.0-10ubuntu2) 9.3.0
Copyright (C) 2019 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.

**Comment by hjagodzinski** [comment]
@nsmohan if you're still interested in using C-Mock, please try to use the latest master branch. @krzbe has prepared a fix in #14 which should resolve compilation errors you had encountered.
