### ISSUE TITLE
How to call real function with CMOCK_MOCK_FUNCTIONn macros

### ISSUE THREAD

**Issue by devesh25427** [hjagodzinski/C-Mock#17]
I am trying to use new style CMOCK_MOCK_FUNCTIONn macros and want to invoke real function in expectation. I am unable to figure out how to do that?

**Comment by hjagodzinski** [comment]
@devesh25427 please take a look at section [Specifying expectations](https://github.com/hjagodzinski/C-Mock#specifying-expectations). The botom line is:

> The functions are mocked as long as its corresponding mocker class instance exists

If not mocked, the real function will be called.

**Comment by devesh25427** [comment]
@hjagodzinski thanks for reply. I understood that real function is called when there is no mock class instance. Earlier I was able to call real function using Invoke(<mock_class_name>::real) because there was a static member in class pointing to real function. I can still see static real function pointer created by CMOCK_MOCK_FUNCTIONn macro but don't know how to call it.
Sometimes I need to call real instance while setting expectation.

**Comment by hjagodzinski** [comment]
I see now what you're after. Unfortunately there is no support for calling a real function while specifying expectations. Internally C Mock keeps pointer to a real function and you could use that but it's far from being ideal. I will look into ways to expose a real function so it can be used in cases like yours.

**Comment by devesh25427** [comment]
Thanks @hjagodzinski

**Comment by hjagodzinski** [comment]
@devesh25427 in case you are still interested I have created pull request #22 which provides the means to call a real function when using the `CMockMocker` class for mocking.
