### ISSUE TITLE
Add release for current code

### ISSUE THREAD

**Issue by dolevelbaz** [hjagodzinski/C-Mock#20]
Please add a tagged release for the current version on master, so one can use it as CMake dependency easily along with GTest 1.10.

**Comment by hjagodzinski** [comment]
I was planning on adding a one more change hence I decided to wait before making a release. A few moths later it turns out I haven't done neither of those things :) I've create a new release [v0.3.0](https://github.com/hjagodzinski/C-Mock/releases/tag/v0.3.0).

**Comment by dolevelbaz** [comment]
Awesome, thanks!
