### ISSUE TITLE
Code and tests does not comile

### ISSUE THREAD

**Issue by RomanUlan** [hjagodzinski/C-Mock#21]
Hi!
First of all I've to say that I like your extension very much.
It seems that not the latest version does not compile (even your tests):
C-Mock/test$ make
```
cc -c -fPIC math.c -o math.o
cc -shared -Wl,-soname,/home/roman/Documents/trainings/c/c-modern/libs/C-Mock/test/libmath.so -o libmath.so math.o
g++ -c -I'/home/roman/Documents/trainings/c/c-modern/libs/C-Mock/include' -I../../googletest/googlemock/include -I../../googletest/googletest/include add_function_mock.cc -o add_function_mock.o
In file included from /home/roman/Documents/trainings/c/c-modern/libs/C-Mock/include/cmock/cmock.h:38,
                 from add_function_mock.h:4,
                 from add_function_mock.cc:1:
/home/roman/Documents/trainings/c/c-modern/libs/C-Mock/include/cmock/cmock-function-mockers.h:193:27: error: expected identifier before ‘,’ token
  193 |     typedef GMOCK_RESULT_(, F) (*func_type)(GMOCK_ARG_(, 1, F) cmock_a1, \
      |                           ^
add_function_mock.h:8:1: note: in expansion of macro ‘DECLARE_FUNCTION_MOCK2’
    8 | DECLARE_FUNCTION_MOCK2(AddFunctionMock, add, int(int, int));
      | ^~~~~~~~~~~~~~~~~~~~~~
/home/roman/Documents/trainings/c/c-modern/libs/C-Mock/include/cmock/cmock-function-mockers.h:193:33: error: expected identifier before ‘*’ token
  193 |     typedef GMOCK_RESULT_(, F) (*func_type)(GMOCK_ARG_(, 1, F) cmock_a1, \
      |                                 ^
add_function_mock.h:8:1: note: in expansion of macro ‘DECLARE_FUNCTION_MOCK2’
    8 | DECLARE_FUNCTION_MOCK2(AddFunctionMock, add, int(int, int));
```

Version of my compiler:
$ g++ --version
```
g++ (Ubuntu 9.3.0-17ubuntu1~20.04) 9.3.0
Copyright (C) 2019 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
```

Version of googletest: actual master for day of 29.03.2021.

**Comment by hjagodzinski** [comment]
Hi @RomanUlan, C-Mock leverages internal Google Mock macros that have been deleted since the release 1.10.0 hence compilation errors. I've updated C-Mock to use the latest ones available in the current master branch.

I'm glad you like this project. Do you mind asking me what kind of project you use it for? I'm just curious 😉

**Comment by RomanUlan** [comment]
Hi @hjagodzinski!
Sorry for late reply! Quite busy days behind me.
Anyway and long story short: I started with your framework in 2013 for on of our bigger customer from Ireland who delivers new generation switches for data centers. There was a bunch of code in C in user and kernel land (Linux) where we had strong KPIs for code quality verification (coverage: 100% functions, 75% of branches). Then I've started to use C-mock for other projects e.g. IoT platforms (still mostly networking code) and today I use it in project where we deliver a bit more advanced routers for office and home spaces (again networking).
I'm also a SW engineering trainer. I do a lot of trainings and for C parts (dev tests) i always recommend you framework as a very helpful tool!
Once you would like to know more, drop me an email, then I'll share you my mobile #.
 
BIG Thank you for taking a quick action!

**Comment by hjagodzinski** [comment]
Hi @RomanUlan,

No worries I can absolutely relate to that.

The projects you work on sound really interesting. I'm continuously surprised somebody is actually using C-Mock. I'm glad you find C-Mock useful to a degree you recommend during your classes. It turns out you started using it from the start of the project as it dates back to 2013.
